### ISSUE TITLE
Regarding the new opcodes

### ISSUE THREAD

**Issue by XMDS** [AndroidModLoader/GTA_CLEOMod#2]
I'm not sure if I should tell you this, but my XCommands plugin has actually added almost 95% of the cleo4 opcodes and it supports all GTA games. I think there's no need for CleoMod to add them because it's duplicating work, and I don't think your implementation is good and can solve some implementation issues in the short term, which is unstable. You can spend your time on your other projects, such as SAUtils and ImGui plugins. I think SAUtils is your best plugin and you may need more time to add new features and APIs.
I will release the XCommands plugin next week, which is very stable. It also has other powerful op functions.

**Comment by XMDS** [comment]
@RusJJ I'm requesting this again, I don't want the results of my short writing time to be wasted. I'm requesting it again, thank you.

**Comment by RusJJ** [comment]
We needed opcodes a long time ago. We we're waiting for NewCommands which was not even released after an extremely long time. Everyone started asking for and i did what they asked for. I've added only the most usable opcodes (or easy to implement). I dont know what you was doing the long time.

**Comment by XMDS** [comment]
@RusJJ  Yes, you're right. I took a long time. But in reality, I could have released the first version of it a long time ago, but I had difficulty accessing the internet while working. However, now that I have time, I just need to update them to release the first version. I apologize again, but please give me one more week, I'm sure I'll release it.
