### ISSUE TITLE
[BUG] SCM FUNCTION : with parameter string

### ISSUE THREAD

**Issue by MatiDragon-YT** [AndroidModLoader/GTA_CLEOMod#3]
The opcode does not support parameter strings.

**Comment by RusJJ** [comment]
You need to try it now, was my mistake

**Comment by MatiDragon-YT** [comment]
you can pass the compiled or give some instructions on how to compile it in Android?

**Comment by RusJJ** [comment]
[Welcome to 2024.](https://github.com/AndroidModLoader/GTA_CLEOMod/actions/runs/8418844247)
