### ISSUE TITLE
[ADD] Remove the delay at startup

### ISSUE THREAD

**Issue by Vladik01-11** [AndroidModLoader/GTA_CLEOMod#5]
By standard, all `*.CSA` scripts start after 3 seconds, all `*.CSI` scripts after 6 seconds (this is when the script selection menu is available).
I suggest to add ini to remove these delays, because they are annoying

**Comment by RusJJ** [comment]
They have a purpose and i'm not lowering the value

**Comment by Vladik01-11** [comment]
do they have any meaningful role to play?
